In [1]:
import tensorflow as tf

print(tf.__version__)

2.2.0


### (AB)^T = A^T * B^T# (AB)^T = A^T * B^T

In [9]:
a = tf.constant([1.2, 3.4, -5.7, -5.3, 8.7, 4.127], shape=(2, 3))

b = tf.constant([34.5, 234.34, 876.43, -5.1243, -675.234, 54.2], shape=(3, 2))

In [10]:
abt = tf.transpose(tf.matmul(a, b))
atbt = tf.matmul(tf.transpose(b), tf.transpose(a))
print(abt)
print(atbt)

tf.Tensor(
[[ 6870.0957    4655.4004  ]
 [  -45.154602 -1062.9001  ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 6870.0957    4655.4004  ]
 [  -45.154602 -1062.9001  ]], shape=(2, 2), dtype=float32)


### Norms

In [11]:
print(tf.norm(a, ord=1, axis=(0, 1)))
print(tf.norm(a, ord='fro', axis=(0, 1)))

tf.Tensor(12.1, shape=(), dtype=float32)
tf.Tensor(12.895818, shape=(), dtype=float32)


In [12]:
a1 = tf.constant([1.2, 3.4, -5.7, -5.3, 8.7, 4.127], shape=(1, 6))
print(tf.norm(a1, ord=1))
print(tf.norm(a1))

tf.Tensor(28.427, shape=(), dtype=float32)
tf.Tensor(12.895818, shape=(), dtype=float32)


In [13]:
b1 = tf.constant([34.5, 234.34, 876.43, -5.1243, -675.234, 54.2], shape=(6, 1))
# print(tf.norm(b, ord=1, axis=(0, 1)))
# print(tf.norm(b, ord='fro', axis=(0, 1)))
print(tf.norm(b1, ord=1))
print(tf.norm(b1))

tf.Tensor(1879.8284, shape=(), dtype=float32)
tf.Tensor(1132.7577, shape=(), dtype=float32)


In [33]:
print(tf.norm(tf.constant([10000., 10001., 10002.,10003.,10004.])))

tf.Tensor(22365.152, shape=(), dtype=float32)


In [25]:
a2 = tf.constant([1., 2., 3., 4., 5., 6., 7., 8., 9., 10., 11., 12., 13., 14., 15., 16.], shape=(4, 4))
b2 = tf.constant([-1., -2., -3., -4., -5., -6., -7., -8., -9., -10., -11., -12.], shape=(4, 3))
print(a2)
print(b2)
print()
print(tf.matmul(a2, b2))

tf.Tensor(
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[ -1.  -2.  -3.]
 [ -4.  -5.  -6.]
 [ -7.  -8.  -9.]
 [-10. -11. -12.]], shape=(4, 3), dtype=float32)

tf.Tensor(
[[ -70.  -80.  -90.]
 [-158. -184. -210.]
 [-246. -288. -330.]
 [-334. -392. -450.]], shape=(4, 3), dtype=float32)


### QR Decomposition

#### square matrix 3x3

In [31]:
qr_data = tf.constant([12, -51, 4, 6, 167, -68, -4, 24, -41], shape=(3, 3))
qr_data = tf.cast(qr_data, tf.float64)
print(tf.linalg.qr(qr_data, 1))

Qr(q=<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[-0.85714286,  0.39428571,  0.33142857],
       [-0.42857143, -0.90285714, -0.03428571],
       [ 0.28571429, -0.17142857,  0.94285714]])>, r=<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[ -14.,  -21.,   14.],
       [   0., -175.,   70.],
       [   0.,    0.,  -35.]])>)


Non-square matrix 4x3

In [32]:
qr_data_r = tf.constant([12, -51, 4, 6, 167, -68, -4, 24, -41, 10, -24, 8],
                        shape=(4, 3))
qr_data_r = tf.cast(qr_data_r, tf.float64)
print(qr_data_r)
qr_result = tf.linalg.qr(qr_data_r, 1)
print(qr_result)
print(tf.matmul(qr_result[0], qr_result[1])) #rounded

tf.Tensor(
[[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -41.]
 [ 10. -24.   8.]], shape=(4, 3), dtype=float64)
Qr(q=<tf.Tensor: shape=(4, 4), dtype=float64, numpy=
array([[-0.69748583,  0.29906048, -0.36166072, -0.54155135],
       [-0.34874292, -0.93281644,  0.02962909, -0.08575542],
       [ 0.23249528, -0.13904489, -0.93080449,  0.24538842],
       [-0.58123819,  0.14519933,  0.04389362,  0.79947024]])>, r=<tf.Tensor: shape=(4, 3), dtype=float64, numpy=
array([[ -17.20465053,   -3.13868625,    6.74236305],
       [   0.        , -177.8542905 ,   71.4901946 ],
       [   0.        ,    0.        ,   35.05271198],
       [   0.        ,    0.        ,    0.        ]])>)
tf.Tensor(
[[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -41.]
 [ 10. -24.   8.]], shape=(4, 3), dtype=float64)


Non-square matrix 3x4

In [28]:
qr_data_c = tf.constant([12, -51, 4, 6, 167, -68, -4, 24, -41, 10, -24, 8],
                        shape=(3, 4))
qr_data_c = tf.cast(qr_data_c, tf.float64)
print(qr_data_c)
print(tf.linalg.qr(qr_data_c, 1))

tf.Tensor(
[[ 12. -51.   4.   6.]
 [167. -68.  -4.  24.]
 [-41.  10. -24.   8.]], shape=(3, 4), dtype=float64)
Qr(q=<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[-0.06961466,  0.9878042 , -0.13927189],
       [-0.96880397, -0.03365772,  0.24553211],
       [ 0.23785008,  0.1520198 ,  0.95933171]])>, r=<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[-172.37749273,   71.80751851,   -2.11164459,  -21.7661827 ],
       [   0.        ,  -46.56909152,    0.43737254,    6.33519837],
       [   0.        ,    0.        ,  -24.56317696,   12.73179297]])>)


In [7]:
import numpy as np

def householder(A):
    """     
        Args:
        -   A: A n-d numpy array of shape (n,n) 

        Returns:
        -   P: A n-d numpy array of shape (n,n), representing 
                a Householder matrix
    """
    n, _ = A.shape
    x = A[:,0].reshape(n,1)
    e1 = np.zeros((n,1))
    e1[0] = 1.
    v = np.sign(x[0]) * np.linalg.norm(x) * e1 + x
    # divide by 2-norm squared
    P = np.eye(n) - 2 * v.dot(v.T)/v.T.dot(v)
    return P

def qr_decomposition(A):
    """ 
    Form the QR decomposition of A by using
    Householder matrices.
    """
    n, _ = A.shape
    P = np.zeros((n-1,n,n))
    R = A
    for i in range(n-1):

        P[i] = np.eye(n)
        # modify lower-right block
        P[i,i:,i:] = householder(R[i:,i:])
        print(f'On iter {i}', np.round(P[i].dot(R), 1))
        R = P[i].dot(R)

    Q_T = np.eye(n)
    for i in range(n-1):
        Q_T = P[i].dot(Q_T)

    Q = Q_T.T
    return Q, R

def qr_decomposition(A):
    """ 
    Form the QR decomposition of A by using
    Householder matrices.
    """
    n, _ = A.shape
    P = np.zeros((n-1,n,n))
    R = A
    for i in range(n-1):
        print('>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>')
        P[i] = np.eye(n)
        # modify lower-right block
        P[i,i:,i:] = householder(R[i:,i:])
        print(f'On iter {i}', np.round(P[i].dot(R), 1))
        R = P[i].dot(R)
        print('++++++++++++++++++++++++++++++++++++++++++++++++')
        print(R)
        print('-------------')
        print(P[i])
        print('<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n\n')

    Q_T = np.eye(n)
    for i in range(n-1):
        Q_T = P[i].dot(Q_T)

    Q = Q_T.T
    return Q, R

def qr_demo():
    """ """
    # n = 4
    # A = np.random.randint(-100,100,(n,n))
    # A = np.array([
    #     [6, 6, -77, 59],
    #     [-13, 20, -81, 1],
    #     [-33, -35, -65, -74],
    #     [98, 92, 42, 2]
    # ])
    A = np.array([
        [12, -51, 4], 
        [6, 167, -68], 
        [-4, 24, -41], 
        [10, -24, 8]
    ])

    Q,R = qr_decomposition(A)
    print(Q)
    print(R)
    QR = Q.dot(R)
    print('Sum: ', np.absolute(A - QR).sum())
    assert( (A - QR).sum() < 1e-10 )

qr_demo()


On iter 0 [[-17.2  -3.1   6.7]
 [  0.  176.8 -67.4]
 [  0.   17.4 -41.4]
 [  0.   -7.6   8.9]]
++++++++++++++++++++++++++++++++++++++++++++++++
[[-1.72046505e+01 -3.13868625e+00  6.74236305e+00]
 [ 1.11022302e-15  1.76832950e+02 -6.74365905e+01]
 [ 0.00000000e+00  1.74446997e+01 -4.13756063e+01]
 [ 0.00000000e+00 -7.61174920e+00  8.93901587e+00]]
-------------
[[-0.69748583 -0.34874292  0.23249528 -0.58123819]
 [-0.34874292  0.92835191  0.04776539 -0.11941349]
 [ 0.23249528  0.04776539  0.9681564   0.07960899]
 [-0.58123819 -0.11941349  0.07960899  0.80097752]]
On iter 1 [[ -17.2   -3.1    6.7]
 [  -0.  -177.9   71.5]
 [  -0.    -0.   -34.5]
 [   0.     0.     6. ]]
++++++++++++++++++++++++++++++++++++++++++++++++
[[-1.72046505e+01 -3.13868625e+00  6.74236305e+00]
 [-1.10384750e-15 -1.77854290e+02  7.14901946e+01]
 [-1.08895361e-16 -3.62904151e-15 -3.45427244e+01]
 [ 4.75149584e-17  8.88178420e-16  5.95758400e+00]]
-------------
[[ 1.          0.          0.          0.        ]
 [ 0. 