In [16]:
import tensorflow as tf

print(tf.__version__)

2.2.0


### (AB)^T = A^T * B^T# (AB)^T = A^T * B^T

In [9]:
a = tf.constant([1.2, 3.4, -5.7, -5.3, 8.7, 4.127], shape=(2, 3))

b = tf.constant([34.5, 234.34, 876.43, -5.1243, -675.234, 54.2], shape=(3, 2))

In [10]:
abt = tf.transpose(tf.matmul(a, b))
atbt = tf.matmul(tf.transpose(b), tf.transpose(a))
print(abt)
print(atbt)

tf.Tensor(
[[ 6870.0957    4655.4004  ]
 [  -45.154602 -1062.9001  ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 6870.0957    4655.4004  ]
 [  -45.154602 -1062.9001  ]], shape=(2, 2), dtype=float32)


### Norms

In [11]:
print(tf.norm(a, ord=1, axis=(0, 1)))
print(tf.norm(a, ord='fro', axis=(0, 1)))

tf.Tensor(12.1, shape=(), dtype=float32)
tf.Tensor(12.895818, shape=(), dtype=float32)


In [12]:
a1 = tf.constant([1.2, 3.4, -5.7, -5.3, 8.7, 4.127], shape=(1, 6))
print(tf.norm(a1, ord=1))
print(tf.norm(a1))

tf.Tensor(28.427, shape=(), dtype=float32)
tf.Tensor(12.895818, shape=(), dtype=float32)


In [13]:
b1 = tf.constant([34.5, 234.34, 876.43, -5.1243, -675.234, 54.2], shape=(6, 1))
# print(tf.norm(b, ord=1, axis=(0, 1)))
# print(tf.norm(b, ord='fro', axis=(0, 1)))
print(tf.norm(b1, ord=1))
print(tf.norm(b1))

tf.Tensor(1879.8284, shape=(), dtype=float32)
tf.Tensor(1132.7577, shape=(), dtype=float32)


In [33]:
print(tf.norm(tf.constant([10000., 10001., 10002.,10003.,10004.])))

tf.Tensor(22365.152, shape=(), dtype=float32)


In [25]:
a2 = tf.constant([1., 2., 3., 4., 5., 6., 7., 8., 9., 10., 11., 12., 13., 14., 15., 16.], shape=(4, 4))
b2 = tf.constant([-1., -2., -3., -4., -5., -6., -7., -8., -9., -10., -11., -12.], shape=(4, 3))
print(a2)
print(b2)
print()
print(tf.matmul(a2, b2))

tf.Tensor(
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[ -1.  -2.  -3.]
 [ -4.  -5.  -6.]
 [ -7.  -8.  -9.]
 [-10. -11. -12.]], shape=(4, 3), dtype=float32)

tf.Tensor(
[[ -70.  -80.  -90.]
 [-158. -184. -210.]
 [-246. -288. -330.]
 [-334. -392. -450.]], shape=(4, 3), dtype=float32)


### QR Decomposition

#### square matrix 3x3

In [31]:
qr_data = tf.constant([12, -51, 4, 6, 167, -68, -4, 24, -41], shape=(3, 3))
qr_data = tf.cast(qr_data, tf.float64)
print(tf.linalg.qr(qr_data, 1))

Qr(q=<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[-0.85714286,  0.39428571,  0.33142857],
       [-0.42857143, -0.90285714, -0.03428571],
       [ 0.28571429, -0.17142857,  0.94285714]])>, r=<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[ -14.,  -21.,   14.],
       [   0., -175.,   70.],
       [   0.,    0.,  -35.]])>)


Non-square matrix 4x3

In [32]:
qr_data_r = tf.constant([12, -51, 4, 6, 167, -68, -4, 24, -41, 10, -24, 8],
                        shape=(4, 3))
qr_data_r = tf.cast(qr_data_r, tf.float64)
print(qr_data_r)
qr_result = tf.linalg.qr(qr_data_r, 1)
print(qr_result)
print(tf.matmul(qr_result[0], qr_result[1])) #rounded

tf.Tensor(
[[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -41.]
 [ 10. -24.   8.]], shape=(4, 3), dtype=float64)
Qr(q=<tf.Tensor: shape=(4, 4), dtype=float64, numpy=
array([[-0.69748583,  0.29906048, -0.36166072, -0.54155135],
       [-0.34874292, -0.93281644,  0.02962909, -0.08575542],
       [ 0.23249528, -0.13904489, -0.93080449,  0.24538842],
       [-0.58123819,  0.14519933,  0.04389362,  0.79947024]])>, r=<tf.Tensor: shape=(4, 3), dtype=float64, numpy=
array([[ -17.20465053,   -3.13868625,    6.74236305],
       [   0.        , -177.8542905 ,   71.4901946 ],
       [   0.        ,    0.        ,   35.05271198],
       [   0.        ,    0.        ,    0.        ]])>)
tf.Tensor(
[[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -41.]
 [ 10. -24.   8.]], shape=(4, 3), dtype=float64)


Non-square matrix 3x4

In [28]:
qr_data_c = tf.constant([12, -51, 4, 6, 167, -68, -4, 24, -41, 10, -24, 8],
                        shape=(3, 4))
qr_data_c = tf.cast(qr_data_c, tf.float64)
print(qr_data_c)
print(tf.linalg.qr(qr_data_c, 1))

tf.Tensor(
[[ 12. -51.   4.   6.]
 [167. -68.  -4.  24.]
 [-41.  10. -24.   8.]], shape=(3, 4), dtype=float64)
Qr(q=<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[-0.06961466,  0.9878042 , -0.13927189],
       [-0.96880397, -0.03365772,  0.24553211],
       [ 0.23785008,  0.1520198 ,  0.95933171]])>, r=<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[-172.37749273,   71.80751851,   -2.11164459,  -21.7661827 ],
       [   0.        ,  -46.56909152,    0.43737254,    6.33519837],
       [   0.        ,    0.        ,  -24.56317696,   12.73179297]])>)


In [7]:
import numpy as np
np.set_printoptions(precision = 8, suppress=True)

def householder(A):
    """     
        Args:
        -   A: A n-d numpy array of shape (n,n) 

        Returns:
        -   P: A n-d numpy array of shape (n,n), representing 
                a Householder matrix
    """
    n, _ = A.shape
    x = A[:,0].reshape(n,1)
    e1 = np.zeros((n,1))
    e1[0] = 1.
    v = np.sign(x[0]) * np.linalg.norm(x) * e1 + x
    # divide by 2-norm squared
    P = np.eye(n) - 2 * v.dot(v.T)/v.T.dot(v)
    # print('__________________________')
    # print(P)
    # print('_______________________')
    return P

def qr_decomposition(A):
    """ 
    Form the QR decomposition of A by using
    Householder matrices.
    """
    n, _ = A.shape
    P = np.zeros((n-1,n,n))
    R = A
    for i in range(n-1):
        # print('>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>')
        P[i] = np.eye(n)
        # modify lower-right block
        P[i,i:,i:] = householder(R[i:,i:])
        # print(f'On iter {i}', np.round(P[i].dot(R), 1))
        R = P[i].dot(R)
        # print('++++++++++++++++++++++++++++++++++++++++++++++++')
        # print(R)
        # print('-------------')
        # print(P[i])
        # print('<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n\n')

    Q_T = np.eye(n)
    for i in range(n-1):
        # print('>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>')
        # print(Q_T)
        Q_T = P[i].dot(Q_T)
        # print(Q_T)
        # print('<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<')
        # print()

    Q = Q_T.T
    return Q, R

def qr_demo():
    """ """
    # n = 4
    # A = np.random.randint(-100,100,(n,n))
    A = np.array([
        [6, 6, -77, 59],
        [-13, 20, -81, 1],
        [-33, -35, -65, -74],
        [98, 92, 42, 2]
    ])
    # A = np.array([
    #     [12, -51, 4], 
    #     [6, 167, -68], 
    #     [-4, 24, -41], 
    #     [10, -24, 8]
    # ])

    Q,R = qr_decomposition(A)
    print(Q)
    print(R)
    QR = Q.dot(R)
    print('Sum: ', np.absolute(A - QR).sum())
    assert( (A - QR).sum() < 1e-10 )

qr_demo()


[[-0.05747485 -0.01618887 -0.81502153 -0.57634579]
 [ 0.12452884 -0.98526564 -0.06030549  0.10053572]
 [ 0.31611168  0.15087768 -0.55752515  0.75264536]
 [-0.93875589 -0.0789016  -0.14583849  0.30206465]]
[[-104.39348639  -95.28372262  -65.63627902  -28.53626316]
 [  -0.          -32.34211193   67.93214396  -13.26316034]
 [   0.           -0.           97.75532054   -7.18139135]
 [   0.            0.            0.          -88.9954936 ]]
Sum:  1.9095836023552692e-13


289

### Eigendecomposition

In [19]:
a = tf.constant(
    [1., 7., 3., 7., 4., -5., 3., -5., 6],
    shape=(3, 3)
)
val, vec = tf.linalg.eigh(a)
print(val)
print('======================')
print(vec)

tf.Tensor([-7.0079317  7.0359507 10.971983 ], shape=(3,), dtype=float32)
tf.Tensor(
[[ 0.684154    0.62878436  0.36954555]
 [-0.6139104   0.22292727  0.75724334]
 [-0.39376095  0.74493915 -0.53853375]], shape=(3, 3), dtype=float32)


In [59]:
def manual_eigendecomposition(mat):
    q_s = []
    temp_mat = mat.copy()
    for i in range(3000):
        q, r = qr_decomposition(temp_mat)
        temp_mat = r.dot(q)
        q_s.append(q)

    final_q = np.eye(mat.shape[0])
    for q in q_s:
        final_q = final_q.dot(q)
    
    val = final_q.dot(temp_mat).dot(final_q.T)
    print('>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>')
    print(val)
    print('------------------------')
    print(final_q)
    print('-----------------------')
    print(temp_mat)

testable = np.array(
    [[1., 7., 3.],
    [7., 4., -5.],
    [3., -5., 6.]]
)
manual_eigendecomposition(testable)
print('\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n')
a = tf.constant(
    [1., 7., 3.,
    7., 4., -5.,
    3., -5., 6.],
    shape=(3, 3)
)
val, vec = tf.linalg.eigh(a)
print(val)
print('======================')
print(vec)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[[ 1.  7.  3.]
 [ 7.  4. -5.]
 [ 3. -5.  6.]]
------------------------
[[ 0.36954564 -0.62879238 -0.6841463 ]
 [ 0.75724338 -0.2229199   0.61391301]
 [-0.53853365 -0.74493413  0.39376979]]
-----------------------
[[10.97198268 -0.          0.        ]
 [ 0.          7.03594585 -0.00016823]
 [ 0.         -0.00016823 -7.00792852]]

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

tf.Tensor([-7.0079317  7.0359507 10.971983 ], shape=(3,), dtype=float32)
tf.Tensor(
[[ 0.684154    0.62878436  0.36954555]
 [-0.6139104   0.22292727  0.75724334]
 [-0.39376095  0.74493915 -0.53853375]], shape=(3, 3), dtype=float32)


In [60]:
np.linalg.eig(testable)

(array([-7.00792852,  7.03594585, 10.97198268]),
 array([[ 0.68415383, -0.62878419, -0.36954564],
        [-0.61391034, -0.22292725, -0.75724338],
        [-0.39376087, -0.74493885,  0.53853365]]))

In [61]:
testable1 = np.array(
    [[52, 30, 49, 28],
    [30, 50, 8, 44],
    [49, 8, 46, 16],
    [28, 44, 16, 22]]
)
manual_eigendecomposition(testable1)
print('\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n')
a1 = tf.constant(
    [52., 30., 49., 28.,
    30., 50., 8., 44.,
    49., 8., 46., 16.,
    28., 44., 16., 22.],
    shape=(4, 4)
)
val, vec = tf.linalg.eigh(tf.cast(a1, tf.float32))
print(val)
print('======================')
print(vec)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[[52. 30. 49. 28.]
 [30. 50.  8. 44.]
 [49.  8. 46. 16.]
 [28. 44. 16. 22.]]
------------------------
[[ 0.60945955 -0.29991942 -0.09987744 -0.72707077]
 [ 0.48785283  0.65199675  0.57724915  0.06068999]
 [ 0.4665778  -0.60196233  0.22156327  0.60897966]
 [ 0.41576896  0.35012847 -0.77956246  0.31117293]]
-----------------------
[[132.62787533  -0.           0.          -0.        ]
 [  0.          52.4423       0.           0.        ]
 [  0.           0.         -11.54113078   0.        ]
 [ -0.           0.           0.          -3.52904455]]

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

tf.Tensor([-11.541134   -3.5290391  52.442276  132.6279   ], shape=(4,), dtype=float32)
tf.Tensor(
[[-0.09987721  0.72707087 -0.2999193   0.6094596 ]
 [ 0.57724917 -0.06069009  0.6519968   0.48785287]
 [ 0.22156304 -0.60897964 -0.60196227  0.46657795]
 [-0.7795626  -0.31117266  0.35012853  0.41576898]], shape=(4, 4), dtype=float32)


In [62]:
np.linalg.eig(testable1)

(array([132.62787533,  52.4423    ,  -3.52904455, -11.54113078]),
 array([[-0.60945955, -0.29991942,  0.72707077,  0.09987744],
        [-0.48785283,  0.65199675, -0.06068999, -0.57724915],
        [-0.4665778 , -0.60196233, -0.60897966, -0.22156327],
        [-0.41576896,  0.35012847, -0.31117293,  0.77956246]]))

### Matrix inverse

In [63]:
tf.linalg.inv(a)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.00184843,  0.10536044,  0.08687616],
       [ 0.10536044,  0.00554529, -0.04805916],
       [ 0.08687616, -0.04805915,  0.0831793 ]], dtype=float32)>

In [64]:

np.linalg.inv(testable)

array([[ 0.00184843,  0.10536044,  0.08687616],
       [ 0.10536044,  0.00554529, -0.04805915],
       [ 0.08687616, -0.04805915,  0.0831793 ]])

In [65]:
tf.linalg.inv(a1)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-0.14614311,  0.01601221,  0.13296902,  0.05727113],
       [ 0.0160122 , -0.02001525, -0.02732241,  0.03952217],
       [ 0.13296904, -0.02732241, -0.1007893 , -0.04128718],
       [ 0.05727114,  0.03952217, -0.04128718, -0.0764533 ]],
      dtype=float32)>

In [66]:
np.linalg.inv(testable1)


array([[-0.14614309,  0.0160122 ,  0.13296903,  0.05727115],
       [ 0.0160122 , -0.02001525, -0.0273224 ,  0.03952218],
       [ 0.13296903, -0.0273224 , -0.10078931, -0.04128719],
       [ 0.05727115,  0.03952218, -0.04128719, -0.07645331]])

### Singular value decomposition

In [2]:
import numpy as np

data = np.array(
    [[4, 1, 3],
     [8, 7, -2],
     [1, 5, 4]])

np.linalg.svd(data)

(array([[-0.31196367, -0.34874292,  0.88377432],
        [-0.87632559,  0.46499055, -0.12584614],
        [-0.36705876, -0.81373347, -0.4506725 ]]),
 array([11.97530087,  5.56776436,  3.25456128]),
 array([[-0.72027569, -0.69155144, -0.05440155],
        [ 0.271423  , -0.20878692, -0.93954115],
        [ 0.63838271, -0.69149449,  0.33808711]]))