In [1]:
import tensorflow as tf

print(tf.__version__)

2.2.0


### (AB)^T = A^T * B^T# (AB)^T = A^T * B^T

In [9]:
a = tf.constant([1.2, 3.4, -5.7, -5.3, 8.7, 4.127], shape=(2, 3))

b = tf.constant([34.5, 234.34, 876.43, -5.1243, -675.234, 54.2], shape=(3, 2))

In [10]:
abt = tf.transpose(tf.matmul(a, b))
atbt = tf.matmul(tf.transpose(b), tf.transpose(a))
print(abt)
print(atbt)

tf.Tensor(
[[ 6870.0957    4655.4004  ]
 [  -45.154602 -1062.9001  ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 6870.0957    4655.4004  ]
 [  -45.154602 -1062.9001  ]], shape=(2, 2), dtype=float32)


### Norms

In [11]:
print(tf.norm(a, ord=1, axis=(0, 1)))
print(tf.norm(a, ord='fro', axis=(0, 1)))

tf.Tensor(12.1, shape=(), dtype=float32)
tf.Tensor(12.895818, shape=(), dtype=float32)


In [12]:
a1 = tf.constant([1.2, 3.4, -5.7, -5.3, 8.7, 4.127], shape=(1, 6))
print(tf.norm(a1, ord=1))
print(tf.norm(a1))

tf.Tensor(28.427, shape=(), dtype=float32)
tf.Tensor(12.895818, shape=(), dtype=float32)


In [13]:
b1 = tf.constant([34.5, 234.34, 876.43, -5.1243, -675.234, 54.2], shape=(6, 1))
# print(tf.norm(b, ord=1, axis=(0, 1)))
# print(tf.norm(b, ord='fro', axis=(0, 1)))
print(tf.norm(b1, ord=1))
print(tf.norm(b1))

tf.Tensor(1879.8284, shape=(), dtype=float32)
tf.Tensor(1132.7577, shape=(), dtype=float32)


### QR Decomposition

#### square matrix 3x3

In [14]:
qr_data = tf.constant([12, -51, 4, 6, 167, -68, -4, 24, -41], shape=(3, 3))
qr_data = tf.cast(qr_data, tf.float64)
print(tf.linalg.qr(qr_data))

Qr(q=<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[-0.85714286,  0.39428571,  0.33142857],
       [-0.42857143, -0.90285714, -0.03428571],
       [ 0.28571429, -0.17142857,  0.94285714]])>, r=<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[ -14.,  -21.,   14.],
       [   0., -175.,   70.],
       [   0.,    0.,  -35.]])>)


Non-square matrix 4x3

In [15]:
qr_data_r = tf.constant([12, -51, 4, 6, 167, -68, -4, 24, -41, 10, -24, 8],
                        shape=(4, 3))
qr_data_r = tf.cast(qr_data_r, tf.float64)
print(tf.linalg.qr(qr_data_r))

Qr(q=<tf.Tensor: shape=(4, 3), dtype=float64, numpy=
array([[-0.69748583,  0.29906048, -0.36166072],
       [-0.34874292, -0.93281644,  0.02962909],
       [ 0.23249528, -0.13904489, -0.93080449],
       [-0.58123819,  0.14519933,  0.04389362]])>, r=<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[ -17.20465053,   -3.13868625,    6.74236305],
       [   0.        , -177.8542905 ,   71.4901946 ],
       [   0.        ,    0.        ,   35.05271198]])>)


Non-square matrix 3x4

In [16]:
qr_data_r = tf.constant([12, -51, 4, 6, 167, -68, -4, 24, -41, 10, -24, 8],
                        shape=(3, 4))
qr_data_r = tf.cast(qr_data_r, tf.float64)
print(tf.linalg.qr(qr_data_r))

Qr(q=<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[-0.06961466,  0.9878042 , -0.13927189],
       [-0.96880397, -0.03365772,  0.24553211],
       [ 0.23785008,  0.1520198 ,  0.95933171]])>, r=<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[-172.37749273,   71.80751851,   -2.11164459,  -21.7661827 ],
       [   0.        ,  -46.56909152,    0.43737254,    6.33519837],
       [   0.        ,    0.        ,  -24.56317696,   12.73179297]])>)
